---
title: "Final_Project_Script"
output: html_document
author: "STAT400 Group #5"
---

```{r open csvs }
library(dplyr)
# install.packages("ggplot2") if you are missing it
library(ggplot2)



# Created 4 dataframes from each of the CSV datasets. No need to have files 
# saved in specific location, due to the way the datasets were pulled.
# @Daniel not sure if pulling data from specific remote URL is good idea :v
# made path relative, do you agree?

#active_cases <- read.csv("https://raw.githubusercontent.com/Genes1/stat400_group5_covid/master/data/selected/active.csv")
#recovery_total <- read.csv("https://raw.githubusercontent.com/Genes1/stat400_group5_covid/master/data/selected/cumulative_recoved_total.csv")
#cumulative_recovery_rate <- read.csv("https://raw.githubusercontent.com/Genes1/stat400_group5_covid/master/data/selected/cumulative_recovery_rate.csv")
#recovery_proportion <- read.csv("https://raw.githubusercontent.com/Genes1/stat400_group5_covid/master/data/selected/daily_recovery_proportion.csv")


 transpose_and_rename <- function(df){
   
   # transpose the data, so that making visuals is easier
  df <- as.data.frame(t(df))
  
  # make the states the column names
  names(df) <- df %>% slice(1) %>% unlist()
  
  # slice off the first row, where the state names were
  df <- df %>% slice(-1)
  df$RI <- as.numeric(df$RI)
  df$MD <- as.numeric(df$MD)
  df$VA <- as.numeric(df$VA)
  df$DC <- as.numeric(df$DC)

  return(df)
}

active_cases <- read.csv("../data/selected/active.csv")
active_cases <- transpose_and_rename(active_cases)
#active_cases <- as.data.frame(t(active_cases))
#names(active_cases) <- active_cases %>% slice(1) %>% unlist()
#active_cases <- active_cases %>% slice(-1)

recovery_total <- read.csv("../data/selected/cumulative_recoved_total.csv")
recovery_total <- transpose_and_rename(recovery_total)

cumulative_recovery_rate <- read.csv("../data/selected/cumulative_recovery_rate.csv")
cumulative_recovery_rate <- transpose_and_rename(cumulative_recovery_rate)

recovery_proportion <- read.csv("../data/selected/daily_recovery_proportion.csv")
recovery_proportion <- transpose_and_rename(recovery_proportion)

```


``` {r check NA}

# Ensured no possibility of NA data points influencing further data 
# collection/manipulation.

active_cases <- active_cases[complete.cases(active_cases), ]
recovery_total <- recovery_total[complete.cases(recovery_total), ]
cumulative_recovery_rate <- cumulative_recovery_rate[complete.cases(cumulative_recovery_rate), ]
recovery_proportion <- recovery_proportion[complete.cases(recovery_proportion), ]


```


``` {r return/display dfs}

# Displayed all dataframes

active_cases
recovery_total
cumulative_recovery_rate
recovery_proportion

```

``` {r cumulative recovery total}

factored_dates <- as.factor(rownames(recovery_total))
colors <- c(MD="#5999E3", VA="#E386C9", RI="#E3B159", DC="#77E364")

# cumulative recovery rate

# red - Rhode Island
# blue - virginia
# green - Maryland
# pink - DC



line_size <- 1.2



ggplot(data=recovery_proportion, aes(x=factored_dates, y=RI, group=1, color="RI")) +
  
  #plotting the line data
  geom_line(size=line_size) +
  geom_line(data=cumulative_recovery_rate, aes(x=factored_dates, y=VA, group=2, color="VA"), size=line_size) +
  geom_line(data=cumulative_recovery_rate, aes(x=factored_dates, y=MD, group=3, color="MD"), size=line_size) +
  geom_line(data=cumulative_recovery_rate, aes(x=factored_dates, y=DC, group=4, color="DC"), size=line_size) + 
  
  # scales, titles, labels
  #scale_y_continuous(breaks=seq(0, 25500, 5000), limits = c(0, 25500)) +
  scale_y_continuous(limits = c(0, 1)) +
  scale_x_discrete(breaks=c("X04.12.2020", "X05.01.2020", "X06.01.2020", 
                          "X07.01.2020", "X08.01.2020", "X09.01.2020", 
                          "X10.01.2020", "X11.01.2020", "X12.01.2020")
                 , labels=c("April","May","June",
                            "July", "August", "September", 
                            "October", "November", "December")) +
  ggtitle("Cumulative Recovery Rate") + 
  ylab("Proportion Recovered") + 
  xlab("Time") +
  
  scale_colour_manual(values=colors)+
  
  # general theme
  theme(
        text=element_text(size=12,family="serif"),
        plot.title = element_text(size=20, hjust = 0.5, vjust=3),
        axis.title.x = element_text(size=16, vjust=-2, hjust = 0.47),
        axis.title.y = element_text(size=14, vjust=5),
        plot.margin = unit(c(0.75, 0.5, 0.75, 0.75), "cm"),
        legend.position="right",
        legend.title = element_blank(),
        legend.key.size = unit(1, "cm"),
        legend.key.width = unit(1,"cm"),
        legend.background = element_rect(fill="transparent"),
        legend.box.background = element_rect(fill="transparent"),
        # change background of whole thing
        plot.background = element_rect(fill = "#f9faf5"),
        # change background of inner panel
        panel.background = element_rect(fill = "#dfe7f5"),
         aspect.ratio=6/10
        )






ggplot(data=recovery_proportion, aes(x=factored_dates, y=RI, group=1, color="RI")) +
  
  #plotting the line data
  geom_line(size=line_size) +
  geom_line(data=cumulative_recovery_rate, aes(x=factored_dates, y=VA, group=2, color="VA"), size=line_size) +
  geom_line(data=cumulative_recovery_rate, aes(x=factored_dates, y=MD, group=3, color="MD"), size=line_size) +

  # scales, titles, labels
  #scale_y_continuous(breaks=seq(0, 25500, 5000), limits = c(0, 25500)) +
  scale_y_continuous(limits = c(0, 0.20)) +
  scale_x_discrete(breaks=c("X04.12.2020", "X05.01.2020", "X06.01.2020", 
                          "X07.01.2020", "X08.01.2020", "X09.01.2020", 
                          "X10.01.2020", "X11.01.2020", "X12.01.2020")
                 , labels=c("April","May","June",
                            "July", "August", "September", 
                            "October", "November", "December")) +
  ggtitle("Cumulative Recovery Rate") + 
  ylab("Proportion Recovered") + 
  xlab("Time") +
  
  scale_colour_manual(values=colors)+
  
  # general theme
  theme(
        text=element_text(size=12,family="serif"),
        plot.title = element_text(size=20, hjust = 0.5, vjust=3),
        axis.title.x = element_text(size=16, vjust=-2, hjust = 0.47),
        axis.title.y = element_text(size=14, vjust=5),
        plot.margin = unit(c(0.75, 0.5, 0.75, 0.75), "cm"),
        legend.position="right",
        legend.title = element_blank(),
        legend.key.size = unit(1, "cm"),
        legend.key.width = unit(1,"cm"),
        legend.background = element_rect(fill="transparent"),
        legend.box.background = element_rect(fill="transparent"),
        # change background of whole thing
        plot.background = element_rect(fill = "#f9faf5"),
        # change background of inner panel
        panel.background = element_rect(fill = "#dfe7f5"),
         aspect.ratio=2/10
        ) 



  
```

``` {r daily recovery proportion}
# proportional recovery rate

line_size <- 1
ggplot(data=recovery_proportion, aes(x=factored_dates, y=RI, group=1, color="RI")) +
  
  #plotting the line data
  geom_line(size=line_size) +
  geom_line(data=recovery_proportion, aes(x=factored_dates, y=VA, group=2, color="VA"), size=line_size) +
  geom_line(data=recovery_proportion, aes(x=factored_dates, y=MD, group=3, color="MD"), size=line_size) +
  geom_line(data=recovery_proportion, aes(x=factored_dates, y=DC, group=4, color="DC"), size=line_size) + 
  
  # scales, titles, labels
  #scale_y_continuous(breaks=seq(0, 25500, 5000), limits = c(0, 25500)) +
  scale_y_continuous(limits = c(0, 0.065)) +
  scale_x_discrete(breaks=c("X04.12.2020", "X05.01.2020", "X06.01.2020", 
                          "X07.01.2020", "X08.01.2020", "X09.01.2020", 
                          "X10.01.2020", "X11.01.2020", "X12.01.2020")
                 , labels=c("April","May","June",
                            "July", "August", "September", 
                            "October", "November", "December")) +
  ggtitle("Daily Recovery Proportion") + 
  ylab("Proportion Recovered") + 
  xlab("Time") +
  
  scale_colour_manual(values=colors)+
  
  # general theme
  theme(
        text=element_text(size=12,family="serif"),
        plot.title = element_text(size=20, hjust = 0.5, vjust=3),
        axis.title.x = element_text(size=16, vjust=-2, hjust = 0.47),
        axis.title.y = element_text(size=14, vjust=5),
        plot.margin = unit(c(0.75, 0.5, 0.75, 0.75), "cm"),
        legend.position="right",
        legend.title = element_blank(),
        legend.key.size = unit(1, "cm"),
        legend.key.width = unit(1,"cm"),
        legend.background = element_rect(fill="transparent"),
        legend.box.background = element_rect(fill="transparent"),
        # change background of whole thing
        plot.background = element_rect(fill = "#f9faf5"),
        # change background of inner panel
        panel.background = element_rect(fill = "#dfe7f5"),
         aspect.ratio=6/10
        ) 





# zoom in on non-DC states

ggplot(data=recovery_proportion, aes(x=factored_dates, y=RI, group=1, color="RI")) +
  
  #plotting the line data
  geom_line(size=line_size) +
  geom_line(data=recovery_proportion, aes(x=factored_dates, y=VA, group=2, color="VA"), size=line_size) +
  geom_line(data=recovery_proportion, aes(x=factored_dates, y=MD, group=3, color="MD"), size=line_size) +
  #geom_line(data=recovery_proportion, aes(x=factored_dates, y=DC, group=4, color="DC"), size=line_size) + 
  
  # scales, titles, labels
  #scale_y_continuous(breaks=seq(0, 25500, 5000), limits = c(0, 25500)) +
  scale_y_continuous(limits = c(0, 0.005)) +
  scale_x_discrete(breaks=c("X04.12.2020", "X05.01.2020", "X06.01.2020", 
                          "X07.01.2020", "X08.01.2020", "X09.01.2020", 
                          "X10.01.2020", "X11.01.2020", "X12.01.2020")
                 , labels=c("April","May","June",
                            "July", "August", "September", 
                            "October", "November", "December")) +
  ggtitle("Daily Recovery Proportion") + 
  ylab("Proprtion Recovered") + 
  xlab("Time") +
  
  scale_colour_manual(values=colors)+
  
  # general theme
  theme(
        text=element_text(size=12,family="serif"),
        plot.title = element_text(size=20, hjust = 0.5, vjust=3),
        axis.title.x = element_text(size=16, vjust=-2, hjust = 0.47),
        axis.title.y = element_text(size=14, vjust=5),
        plot.margin = unit(c(0.75, 0.5, 0.75, 0.75), "cm"),
        legend.position="right",
        legend.title = element_blank(),
        legend.key.size = unit(1, "cm"),
        legend.key.width = unit(1,"cm"),
        legend.background = element_rect(fill="transparent"),
        legend.box.background = element_rect(fill="transparent"),
        # change background of whole thing
        plot.background = element_rect(fill = "#f9faf5"),
        # change background of inner panel
        panel.background = element_rect(fill = "#dfe7f5"),
        aspect.ratio=3/10
        ) 

```



```{r cumulative recovery total}


line_size <- 1.2
ggplot(data=recovery_total, aes(x=factored_dates, y=RI, group=1, color="RI")) +
  
  #plotting the line data
  geom_line(size=line_size) +
  geom_line(data=recovery_total, aes(x=factored_dates, y=VA, group=2, color="VA"), size=line_size) +
  geom_line(data=recovery_total, aes(x=factored_dates, y=MD, group=3, color="MD"), size=line_size) +
  geom_line(data=recovery_total, aes(x=factored_dates, y=DC, group=4, color="DC"), size=line_size) + 
  
  # scales, titles, labels
  scale_y_continuous(breaks=seq(0, 25500, 5000), limits = c(0, 25500)) +
  scale_x_discrete(breaks=c("X04.12.2020", "X05.01.2020", "X06.01.2020", 
                          "X07.01.2020", "X08.01.2020", "X09.01.2020", 
                          "X10.01.2020", "X11.01.2020", "X12.01.2020")
                 , labels=c("April","May","June",
                            "July", "August", "September", 
                            "October", "November", "December")) +
  ggtitle("Cumulative Recovery Total") + 
  ylab("Total Recovered") + 
  xlab("Time") +
  
  scale_colour_manual(values=colors)+
  
  # general theme
  theme(
        text=element_text(size=12,family="serif"),
        plot.title = element_text(size=20, hjust = 0.5, vjust=3),
        axis.title.x = element_text(size=16, vjust=-2, hjust = 0.47),
        axis.title.y = element_text(size=14, vjust=5),
        plot.margin = unit(c(0.75, 0.5, 0.75, 0.75), "cm"),
        legend.position="right",
        legend.title = element_blank(),
        legend.key.size = unit(1, "cm"),
        legend.key.width = unit(1,"cm"),
        legend.background = element_rect(fill="transparent"),
        legend.box.background = element_rect(fill="transparent"),
        # change background of whole thing
        plot.background = element_rect(fill = "#f9faf5"),
        # change background of inner panel
        panel.background = element_rect(fill = "#dfe7f5")
        ) 
  




```
